[Variables]

Main =215,180,243
;All text and button colour
Crust =30,30,46
;Window and Bar colour
Mantle =30,30,46
;Outline colour
Red = 243,139,168
Blue = 137,180,250
Yellow = 249,226,175
Green = 166,227,161
Pink = 245,194,231
Peach = 250,179,135
Surface = 49, 50, 68
Base = 30,30,46

;TIME FORMAT
TF =Time.12Hr

;HIDDEN VARIABLES FOR BAR TYPE
SW =0
SS =1

;HIDDEN VARIABLES FOR CLOCK SETTINGS
S12H =0
S24H =1

;BAR HEIGHT 
Size = 1.0

;BROWSER
Browser = Vivaldi

;SEARCH ENGINE
Bing = "www.bing.com"
Google = "www.google.com"

;TERMINUX
command =$UserInput$ 
WindowWidth = 180
WindowWidth2 = 85
WindowHeight1 = 98
WindowHeight2 = 48 

;GLOBAL VARS
Scale = 10
ScrollMouseIncrement = 0.05
