[Variables]

Main =CBA6F7
;All text and button colour
Crust =1e1e2e
;Window and Bar colour
Mantle =CAA5F6
;Outline colour
Base =181825
;Highlight colour
Surface = 49, 50, 68
;Not in use atm
Settings =1e1e2e
;Settings colour

;__________________________________________________________________________________________;                                                                                         
;  __  __  ____   _____ _    _            ______ _          __      ______  _    _ _____   ;
; |  \/  |/ __ \ / ____| |  | |   /\     |  ____| |        /\ \    / / __ \| |  | |  __ \  ;
; | \  / | |  | | |    | |__| |  /  \    | |__  | |       /  \ \  / / |  | | |  | | |__) | ;
; | |\/| | |  | | |    |  __  | / /\ \   |  __| | |      / /\ \ \/ /| |  | | |  | |  _  /  ;
; | |  | | |__| | |____| |  | |/ ____ \  | |    | |____ / ____ \  / | |__| | |__| | | \ \  ;
; |_|  |_|\____/ \_____|_|  |_/_/    \_\ |_|    |______/_/    \_\/   \____/ \____/|_|  \_\ ;
;__________________________________________________________________________________________;                                                                                         
                                                                                         
Red = 243,139,168
Blue = 137,180,250
Yellow = 249,226,175
Green = 166,227,161
Pink = 245,194,231
Peach = 250,179,135



;TIME FORMAT
TF =Time.12Hr

;HIDDEN VARIABLES FOR BAR TYPE
SW =1
SS =0

;HIDDEN VARIABLES FOR CLOCK SETTINGS
S12H =0
S24H =1

;BAR HEIGHT 
Size = 1.0

;BROWSER
Browser =Vivaldi

;TERMINUX
command =$UserInput$ 
WindowWidth = 180
WindowWidth2 = 85
WindowHeight1 = 98
WindowHeight2 = 48 

;GLOBAL VARS
Scale = 10
ScrollMouseIncrement = 0.05
$Icon$=C:\Users\shwet\Documents\Rainmeter\Skins\Windux\@Resources\Images/Browsers/Vivaldi
