[Variables]

;BAR COLORS 
C1 =24,24,37
C2 =165,247,124
C5 =203,166,247
C6 =243, 139, 168
C7 =27,27,41
C8 =165,247,124
C9 =20,20,32
C10 =27,27,41

Red = 243,139,168
Blue = 137,180,250
Yellow = 249,226,175
Green = 166,227,161
Pink = 245,194,231
Peach = 250,179,135

;SETTINGS AND CUSTOM MENU COLORS
SC = #C1#,245

;COMMON COLOR 
HC =203,166,247

;MISC COLORS
Spotippucin Green = 166,227,161
Surface = 49, 50, 68
Base = 30,30,46

;TIME FORMAT
TF =Time.12Hr

;HOME TYPE
HT =Side Home

;HIDDEN VARIABLES FOR HOME TYPE
SF =1
SS =0

;HIDDEN VARIABLES FOR CLOCK SETTINGS
S12H =0
S24H =1

;BAR HEIGHT 
Size = 1.0

;BROWSER
Browser = OperaGX

;SEARCH ENGINE
Bing = "www.bing.com"
Google = "www.google.com"

;TERMINUX
command =$UserInput$ 
WindowWidth = 180
WindowWidth2 = 85
WindowHeight1 = 98
WindowHeight2 = 48 

;GLOBAL VARS
Scale = 10
ScrollMouseIncrement = 0.05
